In [3]:
import torch
import torch.nn as nn
import torch.nn.functional as F
import numpy as np

In [ ]:
torch.tensor([i % 2 for i in range(input_output_size)])

In [4]:
np.random.randint(2, size=10)

array([1, 1, 0, 0, 0, 1, 1, 1, 0, 1])

In [14]:
NUM_LAYERS = 3
masks = torch.randint(2,(NUM_LAYERS,10))
print(masks)

tensor([[1, 0, 1, 0, 0, 1, 1, 1, 1, 1],
        [1, 1, 0, 1, 0, 1, 1, 0, 0, 1],
        [0, 1, 1, 1, 0, 1, 0, 0, 0, 1]])


In [11]:
print(1-mask)

tensor([0, 0, 0, 1, 1, 1, 1, 1, 0, 1])


In [15]:
layers = [
          nn.Conv2d(1,20,5),
          nn.ReLU(),
          nn.Conv2d(20,64,5),
          nn.ReLU()
]

In [16]:
model = nn.Sequential(layers)

TypeError: list is not a Module subclass

In [28]:
a = torch.tensor([1,0,2,3,0,4])
b = torch.tensor([0,1,1,2,1,0])
print(a*b)

tensor([0, 0, 2, 6, 0, 0])


In [29]:
c = torch.tensor([[0,1,1,2,1,0]])
print(a.size())
torch.sum(c,-1).shape


torch.Size([6])


torch.Size([1])