In [3]:
import torch
import torch.nn as nn
import torch.nn.functional as F
import numpy as np

In [ ]:
torch.tensor([i % 2 for i in range(input_output_size)])

In [4]:
np.random.randint(2, size=10)

array([1, 1, 0, 0, 0, 1, 1, 1, 0, 1])

In [14]:
NUM_LAYERS = 3
masks = torch.randint(2,(NUM_LAYERS,10))
print(masks)

tensor([[1, 0, 1, 0, 0, 1, 1, 1, 1, 1],
        [1, 1, 0, 1, 0, 1, 1, 0, 0, 1],
        [0, 1, 1, 1, 0, 1, 0, 0, 0, 1]])


In [11]:
print(1-mask)

tensor([0, 0, 0, 1, 1, 1, 1, 1, 0, 1])


In [15]:
layers = [
          nn.Conv2d(1,20,5),
          nn.ReLU(),
          nn.Conv2d(20,64,5),
          nn.ReLU()
]

In [16]:
model = nn.Sequential(layers)

TypeError: list is not a Module subclass

In [28]:
a = torch.tensor([1,0,2,3,0,4])
b = torch.tensor([0,1,1,2,1,0])
print(a*b)

tensor([0, 0, 2, 6, 0, 0])


In [29]:
c = torch.tensor([[0,1,1,2,1,0]])
print(a.size())
torch.sum(c,-1).shape


torch.Size([6])


torch.Size([1])

In [54]:
import torch.nn as nn
import torch.nn.functional as F

class Model(nn.Module):
    def __init__(self):
        super(Model, self).__init__()
        self.linear1 = nn.Linear(5,10)
        self.activation1 = nn.ReLU()
        self.linear2 = nn.Linear(10,5)
        self.activation2 = nn.ReLU()
        
        self.layers = nn.Sequential(
            self.linear1,
            self.activation1,
            self.linear2,
            self.activation2
            )

    def forward(self, x):
        return self.layers(x)

In [57]:
inp = torch.tensor([[0,1,2,3,4]]).to(torch.float32)
mynet = Model()

In [58]:
mynet(inp)

tensor([[0.0000, 0.0000, 0.0000, 0.0656, 0.2933]], grad_fn=<ReluBackward0>)

In [62]:
batch_inp = torch.tensor([[0,1,2,3,4],
                         [0,2,4,6,8],
                         [0,3,6,9,12]])
batch_inp = batch_inp.to(torch.float32)

In [64]:
mynet(batch_inp)

tensor([[0.0000, 0.0000, 0.0000, 0.0656, 0.2933],
        [0.0000, 0.0000, 0.0000, 0.0972, 0.5257],
        [0.0000, 0.0000, 0.0000, 0.1288, 0.7581]], grad_fn=<ReluBackward0>)